DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS events(
    id INTEGER PRIMARY KEY,
    created_by VARCHAR(25) NOT NULL,
    created_at VARCHAR(25) DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(55) NULL,
    updated_at VARCHAR(25) NULL,
    processed BOOLEAN DEFAULT(FALSE),
    cancelled BOOLEAN DEFAULT(FALSE),
    payload JSON NOT NULL
);
